# -*- coding: utf-8 -*-
"""HW1Problem3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nPP2u0z7dyqEpzffRxsGbgg6R5l09F5b

##Training
"""

from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images.shape

len(train_images)

train_images.ndim

train_images.dtype

train_labels

train_labels.shape

len(train_labels)

"""##Display"""

import matplotlib.pyplot as plt

"""## Average of all Images"""

import numpy as np
average = np.mean(train_images, axis=0)
plt.imshow(average)
plt.show()

"""##Average Individual Digit"""

import numpy as np
for num in range(10):
  image_digit = []
  for i in range(len(train_images)):
    if (num == train_labels[i]):
      image_digit.append(train_images[i])
    
  average = np.mean(image_digit, axis=0)
  plt.imshow(average)
  plt.show()
