# -*- coding: utf-8 -*-
"""HW1_Problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M3NA8wkJbzeyGJVpZNRm8F-kBXkvrD5A

##Problem 1
"""

# Commented out IPython magic to ensure Python compatibility.
from mpl_toolkits import mplot3d
# %matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('seaborn-white')
import numpy as np
from numpy import ma

"""##Local Min"""

def f(x, y):
    return x*x + y*y

x = np.linspace(-6, 6, 30)
y = np.linspace(-6, 6, 30)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)
U = X
V = Z

fig = plt.figure()
ax = plt.axes(projection='3d')
ax.contour3D(X, Y, Z, 150, cmap='RdGy')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z');

ax.scatter(xs=0, ys=0, zs=-1, zdir='z',)
ax.scatter(xs=0, ys=0, zs=0, zdir='z')

x = np.linspace(-5, 5, 30)
y = np.linspace(-5, 5, 30)

plt.contourf(X, Y, Z, 20, cmap='RdGy')
plt.colorbar();
plt.plot(0, 0, 'o', color='black');

plt.figure()
Q = plt.quiver(X, Y, U, V, units='width')

"""## Local Max"""

def f(x, y):
    return (-3*y) + 14*x - 5*(x*x)

x = np.linspace(-6, 6, 30)
y = np.linspace(-6, 6, 30)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)
U = X
V = Z

fig = plt.figure()
ax = plt.axes(projection='3d')
ax.contour3D(X, Y, Z, 150, cmap='RdGy')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z');

x = np.linspace(-5, 5, 30)
y = np.linspace(-5, 5, 30)

plt.contourf(X, Y, Z, 20, cmap='RdGy')
plt.colorbar();
plt.plot(1.4, -5, 'o', color='black');

plt.figure()
Q = plt.quiver(X, Y, U, V, units='width')

"""##Neither"""

def f(x, y):
    return -3*(y*y) + 14*x - 5*(x*x*x)

x = np.linspace(-6, 6, 30)
y = np.linspace(-6, 6, 30)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)
U = X
V = Z

fig = plt.figure()
ax = plt.axes(projection='3d')
ax.contour3D(X, Y, Z, 150, cmap='RdGy')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z');

ax.scatter(xs=1.4, ys=0, zs=0, zdir='z')

plt.contourf(X, Y, Z, 20, cmap='RdGy')
plt.colorbar();
plt.plot(-1, 0, 'o', color='black');

plt.figure()
Q3 = plt.quiver(X, Y, U, V, units='width')
