# -*- coding: utf-8 -*-
"""HW2Problem3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k2WmXokVyyNrrZ3xjs8s3DyYoRX9OII5

##Overfitting
"""

from keras.datasets import cifar10
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten

(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

train_images.shape
len(train_images)
train_images.ndim
train_images.dtype
train_labels
len(train_labels)
class_names = ['airplan', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

train_labels = keras.utils.to_categorical(train_labels, len(class_names))
test_labels = keras.utils.to_categorical(test_labels, len(class_names))

train_images = train_images.astype('float32')
test_images = test_images.astype('float32')
train_images = train_images / 255.0
test_images = test_images / 255.0

model = keras.Sequential([
  keras.layers.Conv2D(32, (3, 3), padding='same',
                 input_shape=(train_images.shape[1:]), activation=tf.nn.relu),
  keras.layers.Conv2D(32, (3, 3), activation=tf.nn.relu),
  keras.layers.MaxPooling2D(pool_size=(2, 2)),
  keras.layers.Conv2D(64, (3, 3), padding='same', activation=tf.nn.relu),
  keras.layers.Conv2D(64, (3, 3), activation=tf.nn.relu),
  keras.layers.MaxPooling2D(pool_size=(2, 2)),
  keras.layers.Flatten(),
  keras.layers.Dense(512, activation=tf.nn.relu),
  keras.layers.Dropout(0.5),
  keras.layers.Dense(10, activation=tf.nn.softmax)
])

# compile the model

opt = keras.optimizers.RMSprop(learning_rate=0.0001, decay=1e-6)
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])


# train the model
epochs = 20
history = model.fit(train_images, 
                      train_labels, 
                      epochs=epochs,  
                      validation_data=(test_images, test_labels),
                      shuffle=True)

history_dict = history.history
acc_values = history_dict['acc']
test_acc_values = history_dict['val_acc']

plt.plot(range(epochs), acc_values, 'bo', label='Training accuracy')
plt.plot(range(epochs), test_acc_values, 'ro', label='Test accuracy')
plt.title('Training and test accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""##Underfitting"""

from keras.datasets import cifar10
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten

(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

train_images.shape
len(train_images)
train_images.ndim
train_images.dtype
train_labels
len(train_labels)
class_names = ['airplan', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

train_labels = keras.utils.to_categorical(train_labels, len(class_names))
test_labels = keras.utils.to_categorical(test_labels, len(class_names))

train_images = train_images.astype('float32')
test_images = test_images.astype('float32')
train_images = train_images / 255.0
test_images = test_images / 255.0

model = keras.Sequential([
  keras.layers.Conv2D(32, (3, 3), padding='same',
                 input_shape=(train_images.shape[1:]), activation=tf.nn.relu),
  keras.layers.Conv2D(32, (3, 3), activation=tf.nn.relu),
  keras.layers.MaxPooling2D(pool_size=(2, 2)),
  keras.layers.Dropout(0.4),
  keras.layers.Conv2D(64, (3, 3), padding='same', activation=tf.nn.relu),
  keras.layers.Conv2D(64, (3, 3), activation=tf.nn.relu),
  keras.layers.MaxPooling2D(pool_size=(2, 2)),
  keras.layers.Dropout(0.4),
  keras.layers.Flatten(),
  keras.layers.Dense(512, activation=tf.nn.relu),
  keras.layers.Dropout(0.5),
  keras.layers.Dense(10, activation=tf.nn.softmax)
])

# compile the model

opt = keras.optimizers.RMSprop(learning_rate=0.0001, decay=1e-6)
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])


# train the model
epochs = 20
history = model.fit(train_images, 
                      train_labels, 
                      epochs=epochs,  
                      validation_data=(test_images, test_labels),
                      shuffle=True)

history_dict = history.history
acc_values = history_dict['acc']
test_acc_values = history_dict['val_acc']

plt.plot(range(epochs), acc_values, 'bo', label='Training accuracy')
plt.plot(range(epochs), test_acc_values, 'ro', label='Test accuracy')
plt.title('Training and test accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""##Good Fit"""

from keras.datasets import cifar10
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten

(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

train_images.shape
len(train_images)
train_images.ndim
train_images.dtype
train_labels
len(train_labels)
class_names = ['airplan', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

train_labels = keras.utils.to_categorical(train_labels, len(class_names))
test_labels = keras.utils.to_categorical(test_labels, len(class_names))

train_images = train_images.astype('float32')
test_images = test_images.astype('float32')
train_images = train_images / 255.0
test_images = test_images / 255.0

model = keras.Sequential([
  keras.layers.Conv2D(32, (3, 3), padding='same',
                 input_shape=(train_images.shape[1:]), activation=tf.nn.relu),
  keras.layers.Conv2D(32, (3, 3), activation=tf.nn.relu),
  keras.layers.MaxPooling2D(pool_size=(2, 2)),
  keras.layers.Dropout(0.2),
  keras.layers.Conv2D(64, (3, 3), padding='same', activation=tf.nn.relu),
  keras.layers.Conv2D(64, (3, 3), activation=tf.nn.relu),
  keras.layers.MaxPooling2D(pool_size=(2, 2)),
  keras.layers.Dropout(0.2),
  keras.layers.Flatten(),
  keras.layers.Dense(512, activation=tf.nn.relu),
  keras.layers.Dropout(0.5),
  keras.layers.Dense(10, activation=tf.nn.softmax)
])

# compile the model

opt = keras.optimizers.RMSprop(learning_rate=0.0001, decay=1e-6)
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])


# train the model
epochs = 20
history = model.fit(train_images, 
                      train_labels, 
                      epochs=epochs,  
                      validation_data=(test_images, test_labels),
                      shuffle=True)

history_dict = history.history
acc_values = history_dict['acc']
test_acc_values = history_dict['val_acc']

plt.plot(range(epochs), acc_values, 'bo', label='Training accuracy')
plt.plot(range(epochs), test_acc_values, 'ro', label='Test accuracy')
plt.title('Training and test accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()
